name: 'Send Message'
description: 'Sends message to the telegram chat'
inputs:
  message:
    required: true

  telegram-token:
    required: true

  telegram-chat-id:
    required: true

runs:
  using: "composite"
  steps:
    - name: Send message
      run: |
        echo $INPUT_MESSAGE > message.txt
        
        echo "Ссылка на пайплайн: $WORKFLOW_RUN_LINK" >> message.txt

        curl -s -X POST "https://api.telegram.org/bot${INPUT_TELEGRAM_TOKEN}/sendMessage" \
        -d "chat_id=${INPUT_TELEGRAM_CHAT_ID}&text=$(cat message.txt)" > /dev/null 2>&1
      shell: bash
      env:
        INPUT_MESSAGE: ${{ inputs.failure-message }}
        INPUT_TELEGRAM_TOKEN: ${{ inputs.telegram-token }}
        INPUT_TELEGRAM_CHAT_ID: ${{ inputs.telegram-chat-id }}
        # WORKFLOW_RUN_LINK var is needed to attach link of the current workflow run to the telegram notification message
        WORKFLOW_RUN_LINK: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
