name: Cache Monitoring on Prod

on:
  push:
  schedule:
    - cron: '30 0 * * *'

jobs:
  validate-cache-headers:
      runs-on: ubuntu-24.04
      timeout-minutes: 10
      steps:
        - uses: actions/checkout@v4
        
        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'
            
        - name: Install dependencies
          run: npm ci
          
        - name: Install Playwright with browsers
          run: npx playwright install --with-deps chromium
          
        - name: Run Playwright test
          id: playwright_test
          run: npx playwright test tests/playwright-tests/cache-checker.spec.ts
          
        - name: Upload results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: cache-validation-results
            path: |
              results.json
              playwright-report/
              test-logs.txt  # Optional: Include the log file in artifacts for download/archive
        
        - name: Send notification to the telegram chat
          if: failure()
          uses: ./.github/actions/send-message-to-telegram
          with:
            message: "Возникла ошибка при проверке хедеров кеширования."
            telegram-token: ${{ secrets.PELICAN_NOTIFICATIONS_BOT_TELEGRAM_TOKEN }}
            telegram-chat-id: ${{ secrets.PELICAN_NOTIFICATIONS_CHAT_ID }}
