name: Perf + Security + Accessibility Monitoring on Prod

on:
  push:
    branches:
      - feature/*

jobs:
  validate-robots:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - name: Validate robots.txt
        id: robots_txt_validation
        run: |
          echo "Fetching robots.txt..."
          curl -sfL https://chelzoo.ru/robots.txt -o robots.txt
          echo "Reading actual content..."
          cat <<EOF > expected_robots.txt
          # *
          User-agent: *
          Disallow: /components

          # Host
          Host: https://chelzoo.ru

          # Sitemaps
          Sitemap: https://chelzoo.ru/api/get-sitemap
          EOF
          echo "Comparing with expected content..."
          if ! diff -u expected_robots.txt robots.txt; then
            echo "❌ robots.txt does not match the expected content."
            exit 1
          fi
          echo "✅ robots.txt matches expected content."

  jmeter-tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm ci

      - name: Cache JMeter
        id: cache-jmeter
        uses: actions/cache@v4
        with:
          path: ./apache-jmeter-5.6.3
          key: jmeter-${{ runner.os }}-v5.6.3

      - name: Download JMeter if not cached
        if: steps.cache-jmeter.outputs.cache-hit != 'true'
        run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Add JMeter to PATH
        run: echo "$PWD/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

      - name: Create report directories
        run: |
          mkdir -p ./report
          mkdir -p ./result

      - name: Run JMeter - Home Page
        run: |
          mkdir -p ./report/homePage
          
          jmeter -n -t ./tests/homePageTest.jmx \
            -l ./report/homePage/homePage.jtl \
            -Jjmeter.save.saveservice.output_format=xml \
            -Jjmeter.save.saveservice.print_field_names=true \
            -Jjmeter.save.saveservice.response_data.on_error=true \
            -Jjmeter.save.saveservice.timestamp_format=ms \
            || echo "JMETER_FAIL=1" >> $GITHUB_ENV

          cp ./report/homePage/homePage.jtl ./result/homePage.jtl

          node tests/homePage-jmeter-report.js || echo "PARSER_FAILED=1" >> $GITHUB_ENV

          if [ -s ./report/homePage/homePage.jtl ]; then
            jmeter -g ./report/homePage/homePage.jtl -o ./report/homePage/html-report || echo "REPORT_GEN_FAIL_homePage=1" >> $GITHUB_ENV
          else
            echo "No JTL produced for homePage — skipping HTML generation"
          fi

      - name: Run JMeter - Documents Page
        run: |
          mkdir -p ./report/documentsPage
          
          jmeter -n -t ./tests/documentsPageTest.jmx \
            -l ./report/documentsPage/documentsPage.jtl \
            -Jjmeter.save.saveservice.output_format=xml \
            -Jjmeter.save.saveservice.print_field_names=true \
            -Jjmeter.save.saveservice.response_data.on_error=true \
            -Jjmeter.save.saveservice.timestamp_format=ms \
            || echo "JMETER_FAIL=1" >> $GITHUB_ENV

          cp ./report/documentsPage/documentsPage.jtl ./result/documentsPage.jtl
          node tests/documentsPage-jmeter-report.js || echo "PARSER_FAILED=1" >> $GITHUB_ENV

          if [ -s ./report/documentsPage/documentsPage.jtl ]; then
            jmeter -g ./report/documentsPage/documentsPage.jtl -o ./report/documentsPage/html-report || echo "REPORT_GEN_FAIL_documentsPage=1" >> $GITHUB_ENV
          else
            echo "No JTL produced for documentsPage — skipping HTML generation"
          fi

      - name: Run JMeter - News Page
        run: |
          mkdir -p ./report/newsPage
          
          jmeter -n -t ./tests/newsPageTest.jmx \
            -l ./report/newsPage/newsPage.jtl \
            -Jjmeter.save.saveservice.output_format=xml \
            -Jjmeter.save.saveservice.print_field_names=true \
            -Jjmeter.save.saveservice.response_data.on_error=true \
            -Jjmeter.save.saveservice.timestamp_format=ms \
            || echo "JMETER_FAIL=1" >> $GITHUB_ENV

          cp ./report/newsPage/newsPage.jtl ./result/newsPage.jtl
          node tests/newsPage-jmeter-report.js || echo "PARSER_FAILED=1" >> $GITHUB_ENV

          if [ -s ./report/newsPage/newsPage.jtl ]; then
            jmeter -g ./report/newsPage/newsPage.jtl -o ./report/newsPage/html-report || echo "REPORT_GEN_FAIL_newsPage=1" >> $GITHUB_ENV
          else
            echo "No JTL produced for newsPage — skipping HTML generation"
          fi

      - name: Verify report files
        run: |
          find ./report -type f | xargs ls -lh
          find ./result -type f | xargs ls -lh

      - name: Upload JMeter Results (JTL)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-result-files
          path: result/

      - name: Upload Full JMeter Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-full-reports
          path: report/
          retention-days: 7

      - name: Fail if any JMeter test failed
        if: env.JMETER_FAIL == '1'
        run: exit 1

      - name: Fail if any parser failed
        if: env.PARSER_FAILED == '1'
        run: exit 1

  lighthouse:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # - name: Cache node modules
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      # - name: Install Node dependencies
      #   run: npm ci

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.15.x

      - name: Run Lighthouse CI - Desktop
        run: lhci autorun --config .lighthouserc.desktop.js

  validate-cache-headers:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - name: Fetch and validate cache headers of CDN media resources
        run: |
          echo "Fetching main page..."
          curl -s https://chelzoo.ru > page.html

          echo "Extracting CDN media resources from HTML..."
          grep -Eo 'https://cdn\.chelzoo\.ru/[^\"\, ]+\.(svg|jpeg|jpg|png|gif|webp)|https://chelzoo\.ru/_next/image\?url=[^\"\, ]+' page.html \
            | sort -u > urls.txt

          echo "Validating Cache-Control headers..."
          EXITCODE=0

          while IFS= read -r url; do
            echo "Checking $url"
            HEADER=$(curl -s -I "$url" | grep -i '^Cache-Control:' | tr -d '\r')

            if [[ "$url" == *"/_next/static/media/"* ]]; then
              EXPECTED="max-age=31536000"
            elif [[ "$url" == *"image?url=https%3A%2F%2Fcdn.chelzoo.ru%2F_next%2Fstatic%2Fmedia"* ]]; then
              EXPECTED="max-age=31536000"
            elif [[ "$url" == *"image?url=https%3A%2F%2Fstorage.yandexcloud.net"* ]]; then
              EXPECTED="max-age=3600"
            else
              EXPECTED="max-age=3600"
            fi

            if echo "$HEADER" | grep -iq "$EXPECTED"; then
              echo "✅PASSED: $url"
            else
              echo "❌FAILED: $url"
              echo "   Found:    $HEADER"
              echo "   Expected to contain: $EXPECTED"
              EXITCODE=1
            fi
          done < urls.txt

          if [[ $EXITCODE -ne 0 ]]; then
            echo "Some resources have incorrect cache headers."
            exit 1
          else
            echo "All resources have correct cache headers."
          fi


